// <auto-generated />
using System;
using Candidates.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Candidates.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CandidatesDbContext))]
    partial class CandidatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("candidates")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Candidates.Domain.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CommuneCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("commune_code");

                    b.Property<string>("CommuneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("commune_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_name");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DistrictCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("district_code");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district_name");

                    b.Property<short>("Gender")
                        .HasColumnType("smallint")
                        .HasColumnName("gender");

                    b.Property<bool>("HasNgoSupport")
                        .HasColumnType("boolean")
                        .HasColumnName("has_ngo_support");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameKm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_km");

                    b.Property<string>("NgoName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ngo_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("province_code");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province_name");

                    b.Property<Guid?>("SchoolHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_host_id");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("school_name");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VillageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("village_code");

                    b.Property<string>("VillageName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("village_name");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "CreatedAt")
                        .HasDatabaseName("ix_candidates_campaign_created");

                    b.HasIndex("CampaignId", "Phone")
                        .IsUnique()
                        .HasDatabaseName("ux_candidates_campaign_phone");

                    b.HasIndex("CampaignId", "ProvinceName")
                        .HasDatabaseName("ix_candidates_campaign_province");

                    b.HasIndex("CampaignId", "SessionId")
                        .HasDatabaseName("ix_candidates_campaign_session");

                    b.ToTable("candidates", "candidates", t =>
                        {
                            t.HasCheckConstraint("ck_candidates_address_codes", "((province_code IS NULL) = (district_code IS NULL) AND (province_code IS NULL) = (commune_code IS NULL)) AND (village_code IS NULL OR (village_name IS NOT NULL AND province_code IS NOT NULL))");

                            t.HasCheckConstraint("ck_candidates_address_names", "length(btrim(province_name)) > 0 AND length(btrim(district_name)) > 0 AND length(btrim(commune_name)) > 0 AND (village_name IS NULL OR length(btrim(village_name)) > 0)");

                            t.HasCheckConstraint("ck_candidates_gender", "gender IN (1, 2)");

                            t.HasCheckConstraint("ck_candidates_names", "length(btrim(name_km)) > 0 AND length(btrim(name_en)) > 0");

                            t.HasCheckConstraint("ck_candidates_ngo", "(has_ngo_support AND ngo_name IS NOT NULL AND length(btrim(ngo_name)) > 0) OR (NOT has_ngo_support AND ngo_name IS NULL)");

                            t.HasCheckConstraint("ck_candidates_phone", "phone ~ '^0[1-9][0-9]{7,8}$'");

                            t.HasCheckConstraint("ck_candidates_school", "length(btrim(school_name)) > 0");
                        });
                });

            modelBuilder.Entity("Candidates.Domain.CandidateAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by_id");

                    b.Property<string>("ChangedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("changed_by_name");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_audit_log_candidate_id");

                    b.HasIndex("CampaignId", "ChangedAt")
                        .HasDatabaseName("ix_audit_log_campaign_changed_at");

                    b.ToTable("audit_log", "candidates", t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_action", "action IN (1, 2, 3)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
