// <auto-generated />
using System;
using Campaigns.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Campaigns.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CampaignsDbContext))]
    [Migration("20261003023834_InitialCampaigns")]
    partial class InitialCampaigns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("campaigns")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Campaigns.Domain.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("academic_year");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("ExpectedCandidates")
                        .HasColumnType("integer")
                        .HasColumnName("expected_candidates");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_normalized");

                    b.Property<int?>("SeatsAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("seats_available");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_campaigns_created_at");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_campaigns_name_normalized");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_campaigns_status");

                    b.ToTable("campaigns", "campaigns", t =>
                        {
                            t.HasCheckConstraint("ck_campaigns_dates", "start_date IS NULL OR end_date IS NULL OR end_date > start_date");

                            t.HasCheckConstraint("ck_campaigns_expected_candidates", "expected_candidates IS NULL OR expected_candidates > 0");

                            t.HasCheckConstraint("ck_campaigns_seats_available", "seats_available IS NULL OR seats_available > 0");

                            t.HasCheckConstraint("ck_campaigns_seats_within_expected", "seats_available IS NULL OR expected_candidates IS NULL OR seats_available <= expected_candidates");

                            t.HasCheckConstraint("ck_campaigns_status", "status IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Campaigns.Domain.CampaignProvince", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<short>("ProvinceId")
                        .HasColumnType("smallint")
                        .HasColumnName("province_id");

                    b.HasKey("CampaignId", "ProvinceId");

                    b.HasIndex("ProvinceId")
                        .HasDatabaseName("ix_campaign_provinces_province_id");

                    b.ToTable("campaign_provinces", "campaigns");
                });

            modelBuilder.Entity("Campaigns.Domain.Province", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameKm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_km");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_provinces_code");

                    b.ToTable("provinces", "campaigns");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "KH-1",
                            NameEn = "Banteay Meanchey"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "KH-2",
                            NameEn = "Battambang"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "KH-3",
                            NameEn = "Kampong Cham"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "KH-4",
                            NameEn = "Kampong Chhnang"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "KH-5",
                            NameEn = "Kampong Speu"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "KH-6",
                            NameEn = "Kampong Thom"
                        },
                        new
                        {
                            Id = (short)7,
                            Code = "KH-7",
                            NameEn = "Kampot"
                        },
                        new
                        {
                            Id = (short)8,
                            Code = "KH-8",
                            NameEn = "Kandal"
                        },
                        new
                        {
                            Id = (short)9,
                            Code = "KH-9",
                            NameEn = "Koh Kong"
                        },
                        new
                        {
                            Id = (short)10,
                            Code = "KH-10",
                            NameEn = "Kratie"
                        },
                        new
                        {
                            Id = (short)11,
                            Code = "KH-11",
                            NameEn = "Mondulkiri"
                        },
                        new
                        {
                            Id = (short)12,
                            Code = "KH-12",
                            NameEn = "Phnom Penh"
                        },
                        new
                        {
                            Id = (short)13,
                            Code = "KH-13",
                            NameEn = "Preah Vihear"
                        },
                        new
                        {
                            Id = (short)14,
                            Code = "KH-14",
                            NameEn = "Prey Veng"
                        },
                        new
                        {
                            Id = (short)15,
                            Code = "KH-15",
                            NameEn = "Pursat"
                        },
                        new
                        {
                            Id = (short)16,
                            Code = "KH-16",
                            NameEn = "Ratanakiri"
                        },
                        new
                        {
                            Id = (short)17,
                            Code = "KH-17",
                            NameEn = "Siem Reap"
                        },
                        new
                        {
                            Id = (short)18,
                            Code = "KH-18",
                            NameEn = "Preah Sihanouk"
                        },
                        new
                        {
                            Id = (short)19,
                            Code = "KH-19",
                            NameEn = "Stung Treng"
                        },
                        new
                        {
                            Id = (short)20,
                            Code = "KH-20",
                            NameEn = "Svay Rieng"
                        },
                        new
                        {
                            Id = (short)21,
                            Code = "KH-21",
                            NameEn = "Takeo"
                        },
                        new
                        {
                            Id = (short)22,
                            Code = "KH-22",
                            NameEn = "Oddar Meanchey"
                        },
                        new
                        {
                            Id = (short)23,
                            Code = "KH-23",
                            NameEn = "Kep"
                        },
                        new
                        {
                            Id = (short)24,
                            Code = "KH-24",
                            NameEn = "Pailin"
                        },
                        new
                        {
                            Id = (short)25,
                            Code = "KH-25",
                            NameEn = "Tboung Khmum"
                        });
                });

            modelBuilder.Entity("Campaigns.Domain.SetupStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short>("Step")
                        .HasColumnType("smallint")
                        .HasColumnName("step");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Step")
                        .IsUnique()
                        .HasDatabaseName("ux_campaign_setup_steps_campaign_step");

                    b.ToTable("campaign_setup_steps", "campaigns", t =>
                        {
                            t.HasCheckConstraint("ck_campaign_setup_steps_status", "status IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_campaign_setup_steps_step", "step BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Campaigns.Domain.CampaignProvince", b =>
                {
                    b.HasOne("Campaigns.Domain.Campaign", null)
                        .WithMany("Provinces")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Campaigns.Domain.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Campaigns.Domain.SetupStep", b =>
                {
                    b.HasOne("Campaigns.Domain.Campaign", null)
                        .WithMany("Steps")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Campaigns.Domain.Campaign", b =>
                {
                    b.Navigation("Provinces");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
