// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sessions.Infrastructure.Persistence;

#nullable disable

namespace Sessions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SessionsDbContext))]
    [Migration("20261003151330_AllowUnscheduledSessions")]
    partial class AllowUnscheduledSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sessions")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sessions.Domain.InformationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActualFemale")
                        .HasColumnType("integer")
                        .HasColumnName("actual_female");

                    b.Property<int?>("ActualMale")
                        .HasColumnType("integer")
                        .HasColumnName("actual_male");

                    b.Property<string>("AssigneeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assignee_id");

                    b.Property<string>("AssigneeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assignee_name");

                    b.Property<DateTimeOffset?>("AttendanceRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attendance_recorded_at");

                    b.Property<string>("AttendanceRecordedById")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("attendance_recorded_by_id");

                    b.Property<string>("AttendanceRecordedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attendance_recorded_by_name");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_name");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int?>("ExpectedCandidates")
                        .HasColumnType("integer")
                        .HasColumnName("expected_candidates");

                    b.Property<short>("Format")
                        .HasColumnType("smallint")
                        .HasColumnName("format");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<short?>("HostType")
                        .HasColumnType("smallint")
                        .HasColumnName("host_type");

                    b.Property<string>("HostUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("host_user_id");

                    b.Property<string>("HostUserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("host_user_name");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meeting_link");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<short?>("ProvinceId")
                        .HasColumnType("smallint")
                        .HasColumnName("province_id");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId", "Date")
                        .HasDatabaseName("ix_sessions_assignee_date");

                    b.HasIndex("HostId", "Date")
                        .HasDatabaseName("ix_sessions_host_date");

                    b.HasIndex("HostUserId", "Date")
                        .HasDatabaseName("ix_sessions_host_user_date");

                    b.HasIndex("CampaignId", "Date", "StartTime")
                        .HasDatabaseName("ix_sessions_campaign_date");

                    b.ToTable("information_sessions", "sessions", t =>
                        {
                            t.HasCheckConstraint("ck_sessions_attendance", "(actual_female IS NULL) = (actual_male IS NULL) AND (actual_female IS NULL OR (actual_female BETWEEN 0 AND 5000 AND actual_male BETWEEN 0 AND 5000)) AND (status <> 2 OR actual_female IS NOT NULL) AND ((actual_female IS NULL) = (attendance_recorded_at IS NULL))");

                            t.HasCheckConstraint("ck_sessions_cancel_reason", "(status = 3) = (cancel_reason IS NOT NULL)");

                            t.HasCheckConstraint("ck_sessions_expected", "expected_candidates IS NULL OR expected_candidates BETWEEN 0 AND 5000");

                            t.HasCheckConstraint("ck_sessions_format", "format IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_sessions_host_shape", "(host_type IS NULL AND host_user_id IS NULL AND host_user_name IS NULL AND host_id IS NULL) OR (host_type = 1 AND host_user_id IS NOT NULL AND host_user_name IS NOT NULL AND host_id IS NULL) OR (host_type IN (2, 3) AND host_id IS NOT NULL AND host_user_id IS NULL AND host_user_name IS NULL)");

                            t.HasCheckConstraint("ck_sessions_host_type", "host_type IS NULL OR host_type IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_sessions_link", "format = 1 OR meeting_link IS NOT NULL");

                            t.HasCheckConstraint("ck_sessions_scheduled", "(session_date IS NULL) = (start_time IS NULL) AND (session_date IS NULL) = (end_time IS NULL) AND (session_date IS NULL) = (assignee_id IS NULL) AND (session_date IS NULL) = (assignee_name IS NULL) AND (session_date IS NULL) = (host_type IS NULL) AND (session_date IS NOT NULL OR status IN (3, 4))");

                            t.HasCheckConstraint("ck_sessions_status", "status IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_sessions_times", "end_time > start_time");

                            t.HasCheckConstraint("ck_sessions_title", "length(btrim(title)) > 0");

                            t.HasCheckConstraint("ck_sessions_venue", "format = 2 OR venue IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Sessions.Domain.SessionAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by_id");

                    b.Property<string>("ChangedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("changed_by_name");

                    b.Property<short>("Entity")
                        .HasColumnType("smallint")
                        .HasColumnName("entity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_log_entity_id");

                    b.HasIndex("CampaignId", "ChangedAt")
                        .HasDatabaseName("ix_audit_log_campaign_changed_at");

                    b.ToTable("audit_log", "sessions", t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_action", "action IN (1, 2, 3, 4, 5, 6, 7)");

                            t.HasCheckConstraint("ck_audit_log_entity", "entity IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Sessions.Domain.SessionHost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("contact_person");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_name");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_normalized");

                    b.Property<short?>("PartnerKind")
                        .HasColumnType("smallint")
                        .HasColumnName("partner_kind");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Type", "NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_hosts_type_name");

                    b.ToTable("hosts", "sessions", t =>
                        {
                            t.HasCheckConstraint("ck_hosts_contact", "phone IS NOT NULL OR email IS NOT NULL");

                            t.HasCheckConstraint("ck_hosts_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_hosts_partner_kind", "(type = 3) = (partner_kind IS NOT NULL) AND (partner_kind IS NULL OR partner_kind IN (1, 2, 3, 4))");

                            t.HasCheckConstraint("ck_hosts_type", "type IN (2, 3)");
                        });
                });

            modelBuilder.Entity("Sessions.Domain.InformationSession", b =>
                {
                    b.HasOne("Sessions.Domain.SessionHost", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
