// <auto-generated />
using System;
using Eligibility.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eligibility.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EligibilityDbContext))]
    [Migration("20261003041539_InitialEligibility")]
    partial class InitialEligibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("eligibility")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eligibility.Domain.Catalogue.FieldDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("CandidateAttribute")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("candidate_attribute");

                    b.Property<int>("Decimals")
                        .HasColumnType("integer")
                        .HasColumnName("decimals");

                    b.Property<short>("Derivation")
                        .HasColumnType("smallint")
                        .HasColumnName("derivation");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("min_value");

                    b.Property<short?>("OptionsSource")
                        .HasColumnType("smallint")
                        .HasColumnName("options_source");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<short>("ValueType")
                        .HasColumnType("smallint")
                        .HasColumnName("value_type");

                    b.HasKey("Key");

                    b.ToTable("fields", "eligibility", t =>
                        {
                            t.HasCheckConstraint("ck_fields_decimals", "decimals >= 0");

                            t.HasCheckConstraint("ck_fields_value_type", "value_type IN (1, 2, 3, 4)");
                        });

                    b.HasData(
                        new
                        {
                            Key = "age",
                            CandidateAttribute = "date_of_birth",
                            Decimals = 0,
                            Derivation = (short)1,
                            Label = "Age",
                            MaxValue = 120m,
                            MinValue = 0m,
                            Position = 1,
                            Unit = "years",
                            ValueType = (short)1
                        },
                        new
                        {
                            Key = "gender",
                            CandidateAttribute = "gender",
                            Decimals = 0,
                            Derivation = (short)0,
                            Label = "Gender",
                            OptionsSource = (short)1,
                            Position = 2,
                            ValueType = (short)2
                        },
                        new
                        {
                            Key = "province",
                            CandidateAttribute = "province",
                            Decimals = 0,
                            Derivation = (short)0,
                            Label = "Province",
                            OptionsSource = (short)2,
                            Position = 3,
                            ValueType = (short)2
                        },
                        new
                        {
                            Key = "highest_grade",
                            CandidateAttribute = "highest_grade",
                            Decimals = 0,
                            Derivation = (short)0,
                            Label = "Highest grade completed",
                            OptionsSource = (short)1,
                            Position = 4,
                            ValueType = (short)2
                        },
                        new
                        {
                            Key = "grade12_result",
                            CandidateAttribute = "grade12_result",
                            Decimals = 0,
                            Derivation = (short)0,
                            Label = "Grade 12 exam result",
                            OptionsSource = (short)1,
                            Position = 5,
                            ValueType = (short)2
                        },
                        new
                        {
                            Key = "family_income",
                            CandidateAttribute = "family_income",
                            Decimals = 2,
                            Derivation = (short)0,
                            Label = "Family monthly income",
                            MinValue = 0m,
                            Position = 6,
                            Unit = "USD",
                            ValueType = (short)1
                        },
                        new
                        {
                            Key = "marital_status",
                            CandidateAttribute = "marital_status",
                            Decimals = 0,
                            Derivation = (short)0,
                            Label = "Marital status",
                            OptionsSource = (short)1,
                            Position = 7,
                            ValueType = (short)2
                        },
                        new
                        {
                            Key = "attended_info_session",
                            CandidateAttribute = "attended_info_session",
                            Decimals = 0,
                            Derivation = (short)0,
                            Label = "Attended an information session",
                            Position = 8,
                            ValueType = (short)3
                        });
                });

            modelBuilder.Entity("Eligibility.Domain.Catalogue.FieldOption", b =>
                {
                    b.Property<string>("FieldKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("field_key");

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("FieldKey", "Key");

                    b.ToTable("field_options", "eligibility");

                    b.HasData(
                        new
                        {
                            FieldKey = "gender",
                            Key = "female",
                            Label = "Female",
                            Position = 1
                        },
                        new
                        {
                            FieldKey = "gender",
                            Key = "male",
                            Label = "Male",
                            Position = 2
                        },
                        new
                        {
                            FieldKey = "highest_grade",
                            Key = "grade_9",
                            Label = "Grade 9",
                            Position = 1
                        },
                        new
                        {
                            FieldKey = "highest_grade",
                            Key = "grade_10",
                            Label = "Grade 10",
                            Position = 2
                        },
                        new
                        {
                            FieldKey = "highest_grade",
                            Key = "grade_11",
                            Label = "Grade 11",
                            Position = 3
                        },
                        new
                        {
                            FieldKey = "highest_grade",
                            Key = "grade_12",
                            Label = "Grade 12",
                            Position = 4
                        },
                        new
                        {
                            FieldKey = "highest_grade",
                            Key = "diploma_or_higher",
                            Label = "Diploma or higher",
                            Position = 5
                        },
                        new
                        {
                            FieldKey = "grade12_result",
                            Key = "A",
                            Label = "A",
                            Position = 1
                        },
                        new
                        {
                            FieldKey = "grade12_result",
                            Key = "B",
                            Label = "B",
                            Position = 2
                        },
                        new
                        {
                            FieldKey = "grade12_result",
                            Key = "C",
                            Label = "C",
                            Position = 3
                        },
                        new
                        {
                            FieldKey = "grade12_result",
                            Key = "D",
                            Label = "D",
                            Position = 4
                        },
                        new
                        {
                            FieldKey = "grade12_result",
                            Key = "E",
                            Label = "E",
                            Position = 5
                        },
                        new
                        {
                            FieldKey = "grade12_result",
                            Key = "F",
                            Label = "F",
                            Position = 6
                        },
                        new
                        {
                            FieldKey = "marital_status",
                            Key = "single",
                            Label = "Single",
                            Position = 1
                        },
                        new
                        {
                            FieldKey = "marital_status",
                            Key = "married",
                            Label = "Married",
                            Position = 2
                        },
                        new
                        {
                            FieldKey = "marital_status",
                            Key = "divorced",
                            Label = "Divorced",
                            Position = 3
                        },
                        new
                        {
                            FieldKey = "marital_status",
                            Key = "widowed",
                            Label = "Widowed",
                            Position = 4
                        });
                });

            modelBuilder.Entity("Eligibility.Domain.Catalogue.OperatorDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<short>("Arity")
                        .HasColumnType("smallint")
                        .HasColumnName("arity");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<short>("ValueType")
                        .HasColumnType("smallint")
                        .HasColumnName("value_type");

                    b.HasKey("Key");

                    b.HasIndex("ValueType")
                        .HasDatabaseName("ix_operators_value_type");

                    b.ToTable("operators", "eligibility", t =>
                        {
                            t.HasCheckConstraint("ck_operators_arity", "arity IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("ck_operators_value_type", "value_type IN (1, 2, 3, 4)");
                        });

                    b.HasData(
                        new
                        {
                            Key = "equals",
                            Arity = (short)1,
                            Label = "equals",
                            Position = 1,
                            ValueType = (short)1
                        },
                        new
                        {
                            Key = "less_than",
                            Arity = (short)1,
                            Label = "less than",
                            Position = 2,
                            ValueType = (short)1
                        },
                        new
                        {
                            Key = "at_most",
                            Arity = (short)1,
                            Label = "at most",
                            Position = 3,
                            ValueType = (short)1
                        },
                        new
                        {
                            Key = "greater_than",
                            Arity = (short)1,
                            Label = "greater than",
                            Position = 4,
                            ValueType = (short)1
                        },
                        new
                        {
                            Key = "at_least",
                            Arity = (short)1,
                            Label = "at least",
                            Position = 5,
                            ValueType = (short)1
                        },
                        new
                        {
                            Key = "between",
                            Arity = (short)2,
                            Label = "between",
                            Position = 6,
                            ValueType = (short)1
                        },
                        new
                        {
                            Key = "is",
                            Arity = (short)1,
                            Label = "is",
                            Position = 1,
                            ValueType = (short)2
                        },
                        new
                        {
                            Key = "is_not",
                            Arity = (short)1,
                            Label = "is not",
                            Position = 2,
                            ValueType = (short)2
                        },
                        new
                        {
                            Key = "is_one_of",
                            Arity = (short)3,
                            Label = "is one of",
                            Position = 3,
                            ValueType = (short)2
                        },
                        new
                        {
                            Key = "is_none_of",
                            Arity = (short)3,
                            Label = "is none of",
                            Position = 4,
                            ValueType = (short)2
                        },
                        new
                        {
                            Key = "is_yes",
                            Arity = (short)0,
                            Label = "is yes",
                            Position = 1,
                            ValueType = (short)3
                        },
                        new
                        {
                            Key = "is_no",
                            Arity = (short)0,
                            Label = "is no",
                            Position = 2,
                            ValueType = (short)3
                        },
                        new
                        {
                            Key = "before",
                            Arity = (short)1,
                            Label = "before",
                            Position = 1,
                            ValueType = (short)4
                        },
                        new
                        {
                            Key = "after",
                            Arity = (short)1,
                            Label = "after",
                            Position = 2,
                            ValueType = (short)4
                        },
                        new
                        {
                            Key = "date_between",
                            Arity = (short)2,
                            Label = "between",
                            Position = 3,
                            ValueType = (short)4
                        });
                });

            modelBuilder.Entity("Eligibility.Domain.Rules.EligibilityAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by_id");

                    b.Property<string>("ChangedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("changed_by_name");

                    b.Property<short>("Entity")
                        .HasColumnType("smallint")
                        .HasColumnName("entity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_log_entity_id");

                    b.HasIndex("CampaignId", "ChangedAt")
                        .HasDatabaseName("ix_audit_log_campaign_changed_at");

                    b.ToTable("audit_log", "eligibility", t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_action", "action IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_audit_log_entity", "entity IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Eligibility.Domain.Rules.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("field_key");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message");

                    b.Property<string>("OperatorKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operator_key");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.PrimitiveCollection<string[]>("Values")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("values");

                    b.HasKey("Id");

                    b.HasIndex("FieldKey")
                        .HasDatabaseName("ix_rules_field_key");

                    b.HasIndex("OperatorKey");

                    b.HasIndex("GroupId", "FieldKey", "OperatorKey", "Values")
                        .IsUnique()
                        .HasDatabaseName("ux_rules_group_field_operator_values");

                    b.ToTable("rules", "eligibility", t =>
                        {
                            t.HasCheckConstraint("ck_rules_message", "length(btrim(message)) > 0");

                            t.HasCheckConstraint("ck_rules_position", "position >= 0");

                            t.HasCheckConstraint("ck_rules_type", "type IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Eligibility.Domain.Rules.RuleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<short>("Logic")
                        .HasColumnType("smallint")
                        .HasColumnName("logic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Position")
                        .HasDatabaseName("ix_rule_groups_campaign_position");

                    b.ToTable("rule_groups", "eligibility", t =>
                        {
                            t.HasCheckConstraint("ck_rule_groups_logic", "logic IN (1, 2)");

                            t.HasCheckConstraint("ck_rule_groups_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("Eligibility.Domain.Rules.RuleSet", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateOnly?>("AgeReferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("age_reference_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("CampaignId");

                    b.ToTable("rule_sets", "eligibility");
                });

            modelBuilder.Entity("Eligibility.Domain.Catalogue.FieldOption", b =>
                {
                    b.HasOne("Eligibility.Domain.Catalogue.FieldDefinition", null)
                        .WithMany("Options")
                        .HasForeignKey("FieldKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eligibility.Domain.Rules.Rule", b =>
                {
                    b.HasOne("Eligibility.Domain.Catalogue.FieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("FieldKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eligibility.Domain.Rules.RuleGroup", null)
                        .WithMany("Rules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eligibility.Domain.Catalogue.OperatorDefinition", null)
                        .WithMany()
                        .HasForeignKey("OperatorKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Eligibility.Domain.Rules.RuleGroup", b =>
                {
                    b.HasOne("Eligibility.Domain.Rules.RuleSet", null)
                        .WithMany("Groups")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eligibility.Domain.Catalogue.FieldDefinition", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Eligibility.Domain.Rules.RuleGroup", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Eligibility.Domain.Rules.RuleSet", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
